name: Bug Report
description: You found a bug
labels: [bug]
assignees: Michepoli
body:
  - type: checkboxes
    id: check-base
    attributes:
      label: Check Base
      description: base-desc
      options:
        - label: 1-label required
          required: true
        - label: 2-label optional
          required: false

  - type: checkboxes
    id: optional
    attributes:
      label: Optional
      description: optional-desc
      options:
        - label: 1-option
          required: false
        - label: 2-option
          required: false
          
  - type: dropdown
    id: list-selection
    attributes:
      label: Quests chapter
      description: Select the name of the quests chapter
      options:
        - None
        - Welcome
        - Gadgets
        - Primitive Beginnings
        - Steamy Gears
        - Wiring Up
        - Black Sea Logic
        - Space Radiations
    validations:
      required: true
        
  - type: input
    id: text-box
    attributes:
      label: Text Box
      placeholder: example
      description: desc-box
    validations:
      required: true

  - type: textarea
    id: large-text-box
    attributes:
      label: Large Text Box
      description: desc-large-box
      placeholder: example
    validations:
      required: true
      
