name: Bug Report
description: You found a bug
labels: [bug]
assignees: Michepoli
body:
  - type: checkboxes
    id: optional
    attributes:
      label: This issue has already been reported?
      description: Check if your issue is already reported
      options:
        - label: -Yes
          required: false
          
  - type: dropdown
    id: list-selection
    attributes:
      label: Quests chapter
      description: Select the name of the quests chapter
      options:
        - No Chapter
        - Welcome
        - Gadgets
        - Primitive Beginnings
        - Steamy Gears
        - Wiring Up
        - Black Sea Logic
        - Space Radiations
    validations:
      required: true
  
  - type: textarea
    id: large-text-box
    attributes:
      label: Description
      description: Write down the issue you have found and its steps to reproduce it
      placeholder: example
    validations:
      required: true
      
