name: Features Request
description: Feedback
labels: [Enhancement]
assignees: Michepoli
body:
  - type: checkboxes
    id: optional
    attributes:
      label: This feature has already been requested?
      description: Check if your feature is already requested
      options:
        - label: -Yes
          required: false
          
  - type: dropdown
    id: list-selection
    attributes:
      label: Quests chapter
      description: Select the name of the quests chapter where you wanna request your feature
      options:
        - No Chapter
        - Welcome
        - Gadgets
        - Primitive Beginnings
        - Steamy Gears
        - Wiring Up
        - Black Sea Logic
        - Space Radiations
    validations:
      required: true
  
  - type: textarea
    id: large-text-box
    attributes:
      label: Description
      description: Write down your feature/feedback
      placeholder: example
    validations:
      required: true
      
